### PR TITLE
fixed import, changed class name

### LINKED ISSUE #419: Nothing is displayed for 'Arduino Board Configuration'
When I run the 'Arduino Board Configuration' from the ctrl-shift-p or by clicking the board name in the footer, the tab opens with the title but there isn't any content.

The following error is shown in the Developer console.
```
[Embedded Page] Uncaught Invariant Violation: Element type is invalid: expected a string 
(for built-in components) or a class/function (for composite components) but got: object. 
Check the render method of `BoardConfigItemView`. [webview.ts:151]
```
I should mention that I am running Ubuntu 16.04.
Arduino IDE 1.8.4

### PR DESCRIPTION
**Pull request by brndmg**
I am very new to React. But, by trial and error I discovered that the offending line was: 
```
<Select
```
Along with the message below, which I now assume is synonymous with 'class not found': 
```
Element type is invalid: expected a string 
(for built-in components)
```

And the fact that the class was misnamed as `BoardConfigItemView` threw me for a loop since there is already a class with that name.

Closes #419

### CODE REVIEW

**Comment by brndmg** [comment]
@andxu @testforstephen  Can someone review this please?

**Comment by andxu** [comment]
We are on holiday in China, we will look on this PR when we are back at 10.9

**Comment by brndmg** [comment]
Thanks for checking in. Have a good holiday!

**Comment by pedzed** [comment]
Thanks for the PR. This is a real blocker...

File: src/views/app/components/BoardSelector.tsx [hunk 1]
```diff
@@ -3,7 +3,7 @@
 
 import * as React from "react";
 import { Col, DropdownButton, Grid, Row } from "react-bootstrap";
-import * as Select from "react-select";
```
Comment (yaohaizh) [inline src/views/app/components/BoardSelector.tsx]: Could you help check the installed version of react-select on your local environment? It should be on the file of \src\views\node_modules\react-select\package.json file. 

I think this might relate to the version change of react-select.  If this is the case, we need fix down the react-select version for time being in the src\views\package.json ==>     "react-select": "1.0.0-rc.10",

Comment (brndmg) [reply src/views/app/components/BoardSelector.tsx]: In the ` \src\views\node_modules\react-select\package.json`, I see the following.

```json
"_resolved": "https://registry.npmjs.org/react-select/-/react-select-1.0.0-rc.10.tgz",
  "_shasum": "f137346250f9255c979fbfa21860899928772350",
  "_shrinkwrap": null,
  "_spec": "react-select@^1.0.0-rc.4",
```
In the ` \src\views\node_modules\react-select\src\index.js`, I see this:

```js
export default Select;
export {
	Async,
	AsyncCreatable,
	Creatable,
	Value
};
```
Which aligns to the 1.0.0-rc.10 version on GitHub. https://github.com/JedWatson/react-select/blob/v1.0.0-rc.10/src/index.js#L12

in contrast to the older version upon which the extension has a dependency 1.0.0-rc.4 https://github.com/JedWatson/react-select/tree/v1.0.0-rc.4/src/  which doesn't have an explicit export of Select.

I will modify the \src\views\package.json in my PR to reflect the explicit dependency on the correct version of react-select?

Comment (formulahendry) [reply src/views/app/components/BoardSelector.tsx]: The root cause of this issue it that: though we have a `package-lock.json` file, we use the Node 6 (npm 3) in Travis CI, which does not respect the `package-lock.json` file.
To avoid similar issue happen again, we still need to keep the `package-lock.json` file, and update https://github.com/Microsoft/vscode-arduino/blob/master/.travis.yml#L4 to use `node` (latest stable Node.js release) instead of `6`

**Comment by juankgp** [comment]
Sorry I try all changes but I dont have changes,so please could any one do a little manual 
thanks

**Comment by yaohaizh** [comment]
@brndmg Thanks a lo for your contribution. The PR was merged. 

@brndmg @juankgp  The issue is fixed on the latest version. Could you help verify if possible.

**Comment by brndmg** [comment]
I can confirm that the new release `Version 0.2.8` is now working for the `Arduino: Board Configuration`

**Comment by juankgp** [comment]
Thank you so much it work now
